### DISCUSSION TITLE
[GitlabCI][DinD][COMPOSE] Problem with port forwarding when runnig docker compose tests with DinD GitlabCI Runner

### DISCUSSION THREAD

**Discussion by bademux** [testcontainers/testcontainers-java#10272] [Q&A]
Hi,
I'm looking for a help with the problem. There is no way to ping host (in my case its is DinD Gitlab Runner) from container started with DockerCompose module.
If test started on local computer (not DinD), something like configutation below helps:
```yaml
  myservice:
    image: "myservice:latest"
    extra_hosts:
      - "host.testcontainers.internal:host-gateway"
```

But I lack of ideas how to make it work for DinD host. 
I found similar [bug report](https://github.com/testcontainers/testcontainers-java/issues/6932), but it seems that for current testcontainers 1.21 suggested hackfix doesn't work.

Thanks.
