### DISCUSSION TITLE
Could not connect to Ryuk at 172.17.0.1:xxxx

### DISCUSSION THREAD

**Discussion by jelbatnigi** [testcontainers/testcontainers-java#6584] [General]
I can't get a straight solution to this problem. Hopefully someone here can help out .
I have a integrationTest in spring boot application I am running a postgres database testcontainer

`@Container
 public static PostgreSQLContainer container = new PostgreSQLContainer(DB_TEST_CONTAINER_NAME).withDatabaseName(DB_TEST_CONTAINER_DB_NAME)
 .withUsername(DB_TEST_CONTAINER_USER).withPassword(DB_TEST_CONTAINER_PASSWORD);`

When I run my integrationTest from my desktop in runs fine.

When I run it from my jenkins box as part of my build

`./gradlew build`

I get the following error
`java.lang.IllegalStateException: Could not connect to Ryuk at 172.17.0.1:49158`

The test container is trying to run inside a jenkins env which is also running as a container in an EC2 instance. The jenkins container is running with `-v /var/run/docker.sock:/var/run/docker.sock`

I don't know why the Ryuk container cannot run inside a jenkins docker container. Any Docker configuration I have to do here?

**Comment by grey-shirt** [comment]
Hey @jelbatnigi, did you figure this out? 

I'm having the same problem.

**Reply by grey-shirt** [reply]
~~I was running jenkins in a docker container~~. 

~~To fix the issue I was having~~: 
~~`Exception in thread "Thread-3" java.lang.IllegalStateException: Could not connect to Ryuk at 172.17.0.1:32780`~~

~~My _original_ `docker-compose.yml` was running in **bridge** mode~~.

```yml
version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /home/user/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    restart: always
```

~~My updated `docker-compose.yml` puts the network into **host** mode so the container uses the host network stack instead of creating a separate network namespace for the container~~. 

```yml
version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    network_mode: host
    volumes:
      - /home/user/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    restart: always
```

~~Testcontainers are now working on my jenkins pipeline~~.

**Reply by grey-shirt** [reply]
This has been bugging me for a few weeks, despite the above being a working solution I wasn't happy that the jenkins container had full root access to my host machine... That's just an accident waiting to happen.

As I suspected at the time this is not a test container issue, but rather an issue with how the jenkins container is set up.

The original error `java.lang.IllegalStateException: Could not connect to Ryuk at 172.17.0.1:49158` is because passing the docker socket doesn't enable jenkins to manage containers.

The [jenkins docs](https://www.jenkins.io/doc/book/installing/docker/) recommend you create a separate dind (docker in docker) container and allow jenkins to build images in there.

The docs create the jenkins and dind containers from docker commands. I prefer running jenkins from a `docker-compose.yml` file.

**Note** the `Dockerfile` which installs the docker-ce-cli and produces a 'custom' jenkins image.

`./Dockerfile`
```dockerfile
FROM jenkins/jenkins:lts

USER root

RUN apt-get update && apt-get install -y lsb-release

RUN curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
    https://download.docker.com/linux/debian/gpg

RUN echo "deb [arch=$(dpkg --print-architecture) \
    signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
    https://download.docker.com/linux/debian \
    $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list

RUN apt-get update && apt-get install -y docker-ce-cli 

USER jenkins

RUN jenkins-plugin-cli --plugins "blueocean docker-workflow"
``` 

`./docker-compse.yml`
```yml
services:
  docker:
    image: docker:dind
    container_name: docker
    privileged: true
    restart: unless-stopped
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins

  jenkins:
    build:
      context: .
    container_name: jenkins
    restart: unless-stopped
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_TLS_VERIFY=1
      - DOCKER_CERT_PATH=/certs/client
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    networks:
      - jenkins

volumes:
  jenkins-data:
  jenkins-docker-certs:

networks:
  jenkins:

```
