### DISCUSSION TITLE
How to Optimize Git-Actions (like caching run on MySQL container)

### DISCUSSION THREAD

**Discussion by junha-ahn** [testcontainers/testcontainers-java#7322] [Q&A]
Hi I wonder How to optimize my git-actions like caching or etc...

When I **didn't change** my production code / test code (in `src/...`)

It runs during 2 min. I think **It doesn't use any caching**

so I want to optimize my Integration CI on git actions
- At least, How to caching run MySQL container (I think I never changed image tag - or change only table structure)

Is there any official guide or best practice? (git-actions with java/jvm)
and plz give me a available Slack link!

```yml
  integrationTest:
    runs-on: ubuntu-latest
    needs: set-up
    if: always()
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: integrationTest
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        if: always()
        with:
          arguments: integrationTest
```
> from [git actions file](https://github.com/f-lab-clone/ticketing-service/blob/main/.github/workflows/gradle-build-test-lint.yml#L54) 

```
dependencies {
    ...
    integrationTestImplementation("org.springframework.boot:spring-boot-testcontainers")
    integrationTestImplementation("org.testcontainers:junit-jupiter")
    integrationTestImplementation("org.testcontainers:mysql")
}
```
> from [build.gradle.kts](https://github.com/f-lab-clone/ticketing-service/blob/main/build.gradle.kts)

```kotlin
@SpringBootTest
@Testcontainers
abstract class AbstractIntegrationTest {

    companion object {
        val mysqlContainer = MySQLContainer("mysql:8.0.33")
            .withConfigurationOverride("./db/mysql/conf.d")

        @JvmStatic
        @DynamicPropertySource
        fun datasourceConfig(registry: DynamicPropertyRegistry) {
            mysqlContainer.start()
            registry.add("spring.datasource.url", mysqlContainer::getJdbcUrl)
            registry.add("spring.datasource.username", mysqlContainer::getUsername)
            registry.add("spring.datasource.password", mysqlContainer::getPassword)
        }
    }
}

```
> [AbstractIntegrationTest.kt](https://github.com/f-lab-clone/ticketing-service/blob/main/src/integrationTest/kotlin/com/group4/ticketingservice/AbstractIntegrationTest.kt) in [integrationTest folder](https://github.com/f-lab-clone/ticketing-service/tree/main/src/integrationTest)
- use **mysql container**
