### DISCUSSION TITLE
Docker ComposeV2: Access the volume/copy file from container

### DISCUSSION THREAD

**Discussion by hfhbd** [testcontainers/testcontainers-java#8963] [Q&A]
How can I access the volume in my Java/Kotlin test code? Do I miss something?
```yaml
name: foo

services:
  foo:
    image: myImage
    volumes:
      - foo:/foo

volumes:
  foo:
```
There is no file method, like copyFileFromContainer: https://java.testcontainers.org/features/files/

```kotlin
ComposeContainer(File("compose.yaml")).apply {
  withExposedService("foo", 8080, Wait.forHealthcheck())
  start()
}.use { container ->
  container // ?
}
``
