### DISCUSSION TITLE
ComposeContainer mount different file and restart init container

### DISCUSSION THREAD

**Discussion by bilak** [testcontainers/testcontainers-java#9794] [Q&A]
Hello,
I'm using `ComposeContainer` to spin up some `application-container` (e.g. Keycloak) and then configure it by let's say `init-container` (keycloak-config-cli). When `init-container` finishes it works, it just stops with correct exit code.

example of `docker-compose.yml`
```yaml
services:
  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    command: >
      start-dev --log-level="org.keycloak:debug,org.keycloak.transaction:info,org.keycloak.services.scheduled:info"
  keycloak-config-cli:
    image: quay.io/adorsys/keycloak-config-cli:${KEYCLOAK_CONFIG_CLI_VERSION}  
    depends_on:
      - keycloak
    volumes:
      - "./config/realms:/config"
```

I'd like to reuse the initial state of `application-container` and just do some changes in `init-container` (e.g. mount different config files) and then start it again to do a re-configuration stuff for `application-container`. Is that possible with current implementation? Any hints how to do that?

thanks
