### ISSUE TITLE
ElasticsearchContainer and real container conflict

### ISSUE THREAD

**Issue by triberraar** [testcontainers/testcontainers-java#1176]
Hej,
I am running an elastic search container and kibana container locally. But i also want to use the ElasticsearchContainer when running my unit tests, so my real elastic search doesn't get poluted.
If i turn of my real elastic search and kibana, i can run my unit tests and these spawn up a elastic search container. But if i keep my real ones running, the ones from the unit test never boots up.
My guess is that they are trying to form a cluster, the thing i don't want. Anyone got a good suggestion?
Thanks

**Comment by triberraar** [comment]
Well i can run
```
version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    ports:
      - 5601:5601
    networks:
      - esnet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  test_elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: test_elasticsearch
    environment:
      - cluster.name=test-cluster
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - test_esdata:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
      - 9301:9300
    networks:
      - test_esnet
volumes:
  esdata1:
    driver: local
  test_esdata:
    driver: local

networks:
  esnet:
  test_esnet:
```
locally so i can run 2 ES clusters through docker compose.
