### ISSUE TITLE
testcontainers returns wrong mapped port (kafka container from docker-compose file)

### ISSUE THREAD

**Issue by Mutzmann** [testcontainers/testcontainers-java#1187]
Hi guys,
first of all I have to say I like the testcontainers project very much!

I have an issue where testcontainers returns the wrong port for a container which I started from a docker-compose file. I'm runnung Manjaro linux but the problem also appeared on windows 10.

Instead of returning the port which is listed from docker 32871 - **0.0.0.0:32871->9092/tcp** it returns the mapped port for alpine/socat 32873 - **0.0.0.0:32873->2000/tcp**.

My workaround for the moment is to define port mapping in the compose file ("9092:9092"). But I would expect to work testcontainers properly so I can use a random port for the host system.

Could you please have a look? Thanks

Docker ps returns:
```
[rmutze@840G5 ~]$ docker ps
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS              PORTS                                                 NAMES
e30235ec4256        alpine/socat:latest                 "/bin/sh -c 'socat T…"   3 seconds ago       Up 2 seconds        0.0.0.0:32873->2000/tcp, 0.0.0.0:32872->2001/tcp      testcontainers-socat-YE1y6hMv
e9a3b6714d45        wurstmeister/kafka:2.12-2.0.1       "start-kafka.sh"         4 seconds ago       Up 3 seconds        0.0.0.0:32871->9092/tcp, 0.0.0.0:32870->9093/tcp      sggh8ro1v3km_kafka_1
9464c0d4f2be        wurstmeister/zookeeper              "/bin/sh -c '/usr/sb…"   5 seconds ago       Up 3 seconds        22/tcp, 2888/tcp, 3888/tcp, 0.0.0.0:32869->2181/tcp   sggh8ro1v3km_zookeeper_1
f1970c74bcdf        quay.io/testcontainers/ryuk:0.2.2   "/app"                   11 seconds ago      Up 10 seconds       0.0.0.0:32868->8080/tcp                               testcontainers-ryuk-df1799f6-2086-40b7-9035-5432e818bd6d
``` 

But if I print the mapped ports which I receive from testcontainers I get:

```
first mapped port on host for kafka is 32873
second mapped port on host for kafka is 32872
```

Here is my docker-compose_debug.yml:
```yml
version: '2'

services:
  kafka:
    image: wurstmeister/kafka:2.12-2.0.1
    ports:
    - "9092"
    - "9093"
    depends_on:
    - zookeeper
    environment:
      KAFKA_LISTENERS: INSIDE://0.0.0.0:29092, OUTSIDE://0.0.0.0:9092, OUTSIDE_DIND://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092, OUTSIDE://localhost:9092, OUTSIDE_DIND://docker:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT, OUTSIDE:PLAINTEXT, OUTSIDE_DIND:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      -  "2181"
```

And that's my test class:

```java
package de.l.basecamp.lbhkwservice;

import io.vertx.core.json.JsonObject;
import io.vertx.kafka.client.consumer.KafkaConsumer;
import org.junit.Before;
import org.junit.ClassRule;
import org.junit.Test;
import org.testcontainers.containers.DockerComposeContainer;
import java.io.File;


public class IntegrationTests_debug {
    private static KafkaConsumer<String, JsonObject> kafkaConsumer;

    private int firstExposedKafkaPort;
    private int secondExposedKafkaPort;

    
    @ClassRule
    public static DockerComposeContainer dockerComposeEnvironment = new DockerComposeContainer(new File("./src/test/docker-compose_debug.yml"))
            .withExposedService("kafka_1", 9092)
            .withExposedService("kafka_1", 9093);

    @Before
    public void getDockerNetworkParameters(){
        firstExposedKafkaPort = dockerComposeEnvironment.getServicePort("kafka_1", 9092);
        secondExposedKafkaPort = dockerComposeEnvironment.getServicePort("kafka_1", 9093);

        System.out.println(String.format("first mapped port on host for kafka is %d", firstExposedKafkaPort));

        System.out.println(String.format("second mapped port on host for kafka is %d", secondExposedKafkaPort));
    }

    @Test
    public void test () {

    }
}
```

An some information from my system:

```
an 28, 2019 10:06:45 AM org.testcontainers.DockerClientFactory client
INFO: Docker host IP address is localhost
Jan 28, 2019 10:06:46 AM org.testcontainers.DockerClientFactory client
INFO: Connected to docker: 
  Server Version: 18.09.1-ce
  API Version: 1.39
  Operating System: Manjaro Linux
  Total Memory: 15888 MB
Jan 28, 2019 9:33:03 AM org.testcontainers.DockerClientFactory client
INFO: Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
        ℹ︎ Checking the system...
        ✔ Docker version should be at least 1.6.0
        ✔ Docker environment should have more than 2GB free disk space

```
I'm using testcontainers 1.10.5:
```
<dependency>
			<groupId>org.testcontainers</groupId>
			<artifactId>testcontainers</artifactId>
			<version>1.10.5</version>
			<scope>test</scope>
		</dependency>
```
