### ISSUE TITLE
Cannot instantiate a container in Intellij Idea

### ISSUE THREAD

**Issue by driversti** [testcontainers/testcontainers-java#1200]
I've created a spring-boot project from scratch and added the following dependencies:
```xml
<dependency>
	<groupId>org.testcontainers</groupId>
	<artifactId>jdbc</artifactId>
	<version>1.8.2</version>
</dependency>
<dependency>
	<groupId>org.testcontainers</groupId>
	<artifactId>postgresql</artifactId>
	<version>1.8.2</version>
</dependency>
```
and here is my application.yaml

```yaml
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    type: com.zaxxer.hikari.HikariDataSource
    username: postgres
    password: mysecretpassword
    url: jdbc:tc:postgresql:9.6.8://hostname/databasename?TC_DAEMON=true
    platform: org.hibernate.dialect.PostgreSQLDialect
    hikari:
      username: postgres
      password: mysecretpassword
      jdbc-url: jdbc:tc:postgresql:9.6.8://hostname/databasename?TC_DAEMON=true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
```
With `mvn spring-boot:run` the project starts fine, but when I'm running it with IntelliJ Idea I get the following error message: *Database name postgresql not supported*
What I'm doing in a wrong way?
