### ISSUE TITLE
.withNetworkAliases() aliases aren't added to user defined docker network when using .withNetworkMode()

### ISSUE THREAD

**Issue by btpeterson** [testcontainers/testcontainers-java#1221]
When instantiating and running a container like so:
`var container = new GenericContainer("someImageName").withNetworkMode("myUserDefinedNetwork").withNetworkAliases("myAlias");
container.start`

This alias does not work to be addressed other containers in the same network named `"myUserDefinedNetwork"`.

when running the following in command line:
`docker inspect <containerName>`
`"myAlias"` is not included in the list of aliases defined in the network as one would expect.
`"Networks": {
                "myUserDefinedNetwork": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "e78243df71d7"
                    ], . . . `

.withNetworkAliases() method successfully creates the aliases when preceded by .withNetwork() rather than .withNetworkMode(), so I'm guessing there is some difference between `network` and `networkMode` causing this.

Given that there are no warning logs when combining  `.withNetworkMode()` with  `.withNetworkAliases()`, I'm guessing this was not the intended design.

It would be nice if your documentation included a section on these docker networking helper methods.

**Comment by kiview** [comment]
Hey @btpeterson,
what is your use case, to use `withNetworkMode` instead of using Testcontainers' `Network` class in conjuction with `withNetwork`?

You are however right with your observed behavior, see the actual implementation:
https://github.com/testcontainers/testcontainers-java/blob/ef7c5163ba8cdc19f9ee73488d71770ead2ddbcd/core/src/main/java/org/testcontainers/containers/GenericContainer.java#L510-L515

@bsideup I assume it should be fine to set `withAliases` either way?

**Comment by btpeterson** [comment]
This worked for me, thanks @kiview!

In my use case, I'm passing the network name to run the containers on to the application that starts TestContainers.

Is there any specific reason the withNetworkMode() branch of this if/else if doesn't add the aliases?

**Comment by bsideup** [comment]
@kiview @btpeterson 
We intentionally moved `withAliases` under `network != null` to discourage the use of `withNetworkMode` with network id (in fact, it is softly deprecated).

**Comment by btpeterson** [comment]
Okay, but I'm still not understanding the reasoning behind this @bsideup.

If this is discouraged, why is a network id still passed to withNetworkMode() each time? And I don't see how this answers the question of why you're not assigning the aliases (withAliases()) for the [networkMode != null else branch]

**Comment by davidk81** [comment]
It appears this issue is blocking us from using testcontainers on GCP Cloud Build. Our tests were not able run on Cloud Build CI; I believe due to networking issue. Google cloudbuild stated to use an existing network named 'cloudbuild' but TestContainers is not creating the container aliases when created with .withNetworkMode('cloudbuild'). 

The official documentation for GCP instructed to use a named network 'cloudbuild' created during CI and provided this example: https://github.com/GoogleCloudPlatform/cloudbuild-integration-testing

Here is official google documentation for cloud build networking
https://cloud.google.com/cloud-build/docs/overview

Here is discussion on stackoverflow for dns/service discovery across containers on cloudbuild
https://stackoverflow.com/questions/52046609/communicate-between-two-containers-in-google-cloud-build

**Comment by davidk81** [comment]
> It appears this issue is blocking us from using testcontainers on GCP Cloud Build. Our tests were not able run on Cloud Build CI; I believe due to networking issue. Google cloudbuild stated to use an existing network named 'cloudbuild' but TestContainers is not creating the container aliases when created with .withNetworkMode('cloudbuild').
> 
> The official documentation for GCP instructed to use a named network 'cloudbuild' created during CI and provided this example: https://github.com/GoogleCloudPlatform/cloudbuild-integration-testing
> 
> Here is official google documentation for cloud build networking
> https://cloud.google.com/cloud-build/docs/overview
> 
> Here is discussion on stackoverflow for dns/service discovery across containers on cloudbuild
> https://stackoverflow.com/questions/52046609/communicate-between-two-containers-in-google-cloud-build

incase anyone is here trying to get testcontainers to work on cloudbuild, i've finally got it to work using DockerComposeContainer with network set to cloudbuild; also I access by exposed services using hostname from DockerComposeContainer.getServiceHost().

**Comment by bsideup** [comment]
@davidk81
> but TestContainers is not creating the container aliases when created with .withNetworkMode('cloudbuild').

because you shouldn't be using `withNetworkMode`, but `withNetwork`. For external networks, it looks somewhat like this:
```java
.withNetworkAlias("yolo")
.withNetwork(new Network() {
    public String getId() { return "cloudbuild"; }
    public void close() { /* NOOP */ }
});
```

**Comment by popaaaandrei** [comment]
@davidk81 Can you please share your `cloudbuild.yaml` specs? I am having problems running the tests on GCP Cloud Build and I can't get pass `o.t.d.DockerClientProviderStrategy: Could not find a valid Docker environment.`

I tried both `gcr.io/$PROJECT_ID/docker-compose` and `gcr.io/cloud-builders/docker` but the same result.

Thanks!

**Comment by davidk81** [comment]
@popaaaandrei not sure if this will help you, we are using https://github.com/curioswitch/curiostack with gradle with builds. so i am unable to provide a simple, minimum working example, but here's what code we have i can gather relating to testcontainers on GCP Cloud Build. I also remember some issues when simulating cloudbuild locally from ubutu with different docker version vs GCP build server; can't remember the details, but this is our current working set of configs running on Cloud Build.

cloudbuild.yaml (truncated)
```
steps:
- id: configure-docker-authentication
  name: curiostack/java-cloud-builder
  volumes:
    - name: docker-credential
      path: /builder/home/.docker
  entrypoint: gcloud
  args:
    - auth
    - configure-docker
- id: run-integration-test-all
  waitFor:
    - configure-docker-authentication
  name: curiostack/java-cloud-builder
  volumes:
    - name: docker-credential
      path: /root/.docker
  entrypoint: ./gradlew
  args:
    - :testing:integration-test:integrationTestAll
    - --stacktrace
    - --no-daemon
    - --rerun-tasks
timeout: 60m
options:
  machineType: N1_HIGHCPU_32    
```

build.gradle.kts (truncated)
```
task<Test>("integrationTestAll") {
    systemProperty("junit.jupiter.execution.timeout.default", "200s")
    group = LifecycleBasePlugin.VERIFICATION_GROUP
    useJUnitPlatform {
        includeEngines("junit-jupiter", "junit-vintage")
    }
    testClassesDirs = sourceSets["integrationTest"].output.classesDirs
    classpath = sourceSets["integrationTest"].runtimeClasspath
}

dependencies {
    api("com.google.dagger:dagger")
    api("org.testcontainers:testcontainers")
    compileOnly("org.immutables:value-annotations")
    implementation("org.curioswitch.curiostack:curio-server-framework")
    annotationProcessor("com.google.dagger:dagger-compiler")
    annotationProcessor("org.immutables:value")
}
```

docker-compse.yaml (truncated)
```
version: "3.3"
services:

  db:
    image: "<redacted>"
    ports:
      - "3306:3306"

  service:
    image: "<redacted>"
    ports:
      - "8080:8080"

networks:
  default:
      external:
          name: cloudbuild

```

java
```
  public DockerComposeContainer environment;
  environment =
      new DockerComposeContainer(new File("src/main/resources/docker-compose.yml"))
          .withLocalCompose(false)
          .withExposedService(
              "db",
              3306,
              Wait.forHealthcheck().withStartupTimeout(Duration.ofMinutes(60)))
          .withExposedService(
              "service",
              8080,
              Wait.forHealthcheck().withStartupTimeout(Duration.ofMinutes(60)));
```
