### ISSUE TITLE
DockerComposeContainer not working for version 2 of compose format

### ISSUE THREAD

**Issue by jlordiales** [testcontainers/testcontainers-java#146]
Hi,
The DockerComposeContainer functionality seems to be broken if you are using the version 2 format of docker-compose where a new default network is created for each app.

The failing point seems to be the ambassador container, which fails to start with: "Error response from daemon: Cannot link to /5gcpep_api_1, as it does not belong to the default network".

Sample compose file:
```
version: '2'
services:
  db:
    image: postgres
    environment:
        POSTGRES_PASSWORD: test
        POSTGRES_USER: test
  api:
    build: .
    depends_on:
      - db
```
