### ISSUE TITLE
how to use MySQLContainer command

### ISSUE THREAD

**Issue by cheese10yun** [testcontainers/testcontainers-java#2959]
```kotlin
@Container
    protected val mysqlTestContainer = MySQLContainer<Nothing>()
        .apply {
            withDatabaseName("sample")
            withCommand("mysqld", "--ql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION")
            withPrivilegedMode(true)
            withInitScript("set.sql")
            start()
        }
```

I want to remove group by in SQL mode. So I proceeded in the same way as above but it doesn't work.

```yml
version: '3'

services:
  mysql_member:
    container_name: local
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'yun-test'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
...
    command:
      - 'mysqld'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - --'sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
```

Docker compose was used as above.,I want to remove sql_mode group by.
