### ISSUE TITLE
[Help] - How upload files to containers after started compose?

### ISSUE THREAD

**Issue by rgarbin** [testcontainers/testcontainers-java#340]
Hi,

I would like to undestand how I could copy a specific file to my container after up my compose.yml?

```yml
version: "2"
services:
  app:
    image: app:latest
    depends_on:
      - db

  db:
    image: postgres:9.3
```

```java
@ClassRule
public static DockerComposeContainer compose = new DockerComposeContainer(new File("compose.yml"))
```
How I get the container client object from my compose to upload my file to APP container?
