### ISSUE TITLE
Github Action BuildX

### ISSUE THREAD

**Issue by pixie79** [testcontainers/testcontainers-java#3807]
Hi,

Does anybody have an example of using test containers with Github and the BuildX plugin.

I have been attempting to do the following GH action:

```yaml
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64
          allow: "security.insecure,network.host"
```

This fails though on the testcontainers part as I cant see how to tell Github actions to pass the docker.sock through?

Thanks

Mark
