### ISSUE TITLE
Random issues in tests during parallel builds

### ISSUE THREAD

**Issue by Denis220795** [testcontainers/testcontainers-java#3930]
Hello, I'm interesting if smbd also faced with some strange random issues in tests that are using test containers and executed in multiple builds almost at the same time on Jenkins build server (especially RabbitMQ test container)? And if so how you were able to solve it or maybe you can help with the direction to start digging (build server environment, tests themselves, testcontainers etc)?

Problem description:
We have a Linux build server where can be multiple builds happened at the same time and sometimes few tests from multiple services failed with different errors like NullPointerException, Timeouts, Assertion failures etc. When there is only 1-2 build(s) with testcontainers its usually running fine. Also these tests are running fine on my local Windows VM. I noticed that during this test phase multiple containers created and running (then killed after the tests by ryuk container) so tests not reusing already created ones.

Majority of all failures come from RabbitMQ test containers.

Here are some configs that we are using:
`testcontainers.properties` file
```
ryuk.container.image=testcontainersofficial/ryuk:0.3.2
ryuk.container.privileged=true
```

`bootstrap.yml` file:
```
embedded:
  rabbitmq:
    enabled: false   # enabled only for specific tests that needs test container via annotation
    docker-image: 'rabbitmq:3.8.14-management'
    wait-timeout-in-seconds: 30
```

`com.playtika.testcontainers:embedded-rabbitmq:1.82` (tried with latest also didn't help much).

Thanks!
