### ISSUE TITLE
Container reuse across r2dbc:tc and jdbc:tc URLs

### ISSUE THREAD

**Issue by yerzhant** [testcontainers/testcontainers-java#4473]
Could you please enable container reusage across r2dbc and jdbc urls?

Use case (in Spring Boot):
```
spring:
  r2dbc:
    url: r2dbc:tc:postgresql:///test?TC_IMAGE_TAG=12-alpine
  flyway:
    url: jdbc:tc:postgresql:12-alpine:///test
```

https://github.com/testcontainers/testcontainers-java/issues/4282

https://github.com/spring-projects/spring-boot/issues/28076

https://github.com/flyway/flyway/issues/3282
