### ISSUE TITLE
Null pointer exception with getServiceHost

### ISSUE THREAD

**Issue by cesartl** [testcontainers/testcontainers-java#462]
I have the following compose file:

```yaml
version: '2'
services:
  rabbitmq:
    image: "rabbitmq"
    ports:
      - "5672:5672"
  redis:
    image: "redis"
    ports:
      - "6379:6379"
  edge-service:
    image: "***/edge-service:latest"
    ports:
      - "8999:8999"
      - "8998:8998"
    environment:
      - PROFILES=compose
    depends_on:
      - rabbitmq
```
and the following Unit test rule

```java
    @ClassRule
    public static DockerComposeContainer environment =
            new DockerComposeContainer(new File("src/test/resources/compose.yaml"))
                    .withLocalCompose(true)
                    .withExposedService("redis", 6379)
                    .withExposedService("rabbitmq", 5672)
                    .withExposedService("edge-service", 8999);
```

When the unit test starts I can see all the images being run in `docker ps` however once the test executes I get a `NullPointerException` when I do

```
environment.getServiceHost("edge-service", 8999)
```

I'm using 1.4.2.

Is there anything obvious I'm doing wrong?
