### ISSUE TITLE
Starting docker-compose test containers as non-root user

### ISSUE THREAD

**Issue by ben-gineer** [testcontainers/testcontainers-java#4688]
Similar to: https://github.com/testcontainers/testcontainers-java/issues/2590

I'm trying to start our docker-compose based testcontainers tests, and pass in the local username from the running system, in order that the container can write files to mounted volumes with the correct permissions.

I tried a compose with:

```
version: "3.7"
services:
  myservice:
    image: xxx
    user: ${CURRENT_USER}
    ...
    volumes:
      ./target/:/target
```

And passed in CURRENT_USER environment variable to testcontainers using:

```
  env = new DockerComposeContainer(new File("src/main/docker/docker-compose.yml"));
  env.withLocalCompose(true);
  env.withEnv("CURRENT_USER", System.getProperty("user.name"));
```

However, this fails with:
```
Cannot start service my server: unable to find user bmiddleton: no matching entries in passwd file
```
I presume it's looking for that user in the ryuk container, and not the OS - where the user does exist.

How can I get a testcontainers test running from a docker compose file to write its files using the current user of the operating system?
