### ISSUE TITLE
[Bug]: compose bind mount in Gitlab CI

### ISSUE THREAD

**Issue by blockbasti** [testcontainers/testcontainers-java#6673]
### Module

Core

### Testcontainers version

1.17.6

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host Arch

x86

### Docker version

```shell
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:47:01 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:46:56 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

Hi,

i'm trying to use Testcontainers with local docker-compose in my Gitlab CI pipeline.
While the keycloak image is starting, it can't find the realm.json from the bind mount.
When running locally, it works just fine.

My compose file looks like this:
```yaml
version: '3.7'
services:
  iris:
    image: jboss/keycloak:latest
    ports:
      - 8180:8180
    command: ["-Djboss.http.port=8180"]
    networks:
      - backend
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/example-realm.json -Dkeycloak.profile.feature.upload_scripts=enabled
    volumes:
      - ./src/test/resources/sep-quarkus-realm.json:/tmp/example-realm.json
```

I start my containers like this:
```java
new DockerComposeContainer(new File("docker-compose.yml"))
                    .withExposedService(IRIS_SERVICE_NAME, IRIS_PORT, Wait.forLogMessage(".*Admin console listening.*", 1).withStartupTimeout(Duration.ofMinutes(5)))
                    .withLocalCompose(true)
                    .withOptions("--compatibility");
```

After starting the container, i get the following error message in the keycloak container:
```
Caused by: java.io.FileNotFoundException: /tmp/example-realm.json (Is a directory)
```
I tried to use the absolute path in the compose file as well, but nothing changed.

If i create the container "manually" with a generic container, it also works locally and in the pipeline.

Thanks in advance

**Comment by eddumelendez** [comment]
Hi, there is already a [testcontainers-keycloak](https://github.com/dasniko/testcontainers-keycloak) which you can use programatically.

**Comment by blockbasti** [comment]
Thanks, but i know. Keycloak is one of multiple containers i need to start and i wanted to reuse my compose file. Starting keycloak using a generic container works aswell but i wanted to use compose if possible.

**Comment by julienboulay** [comment]
Hi @blockbasti,
I've encountered the same issue with localstack container when started with docker compose on Gitlab (it is working on my laptop). The [initialization hook](https://docs.localstack.cloud/references/init-hooks/) is never triggered in Gitlab, because `/etc/localstack/init/ready.d/init.sh` is never found from the bind mount.

Did you find a solution this Keycloak volume ?

**Comment by julienboulay** [comment]
Here is my docker-compose.yml :

```yaml
version: "3.9"

services:
  localstack:
    networks:
      - ls_network
    image: localstack/localstack:3.4.0
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=1  # enable more verbose logs
      - DOCKER_HOST=unix:///var/run/docker.sock #unix socket to communicate with the docker daemon
      - LOCALSTACK_HOST=localstack # where services are available from other containers
      - ENFORCE_IAM=0 # enforce IAM policies
      - LAMBDA_DOCKER_NETWORK=ls_network
      - LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT=90
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test


    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./target/lambda.jar:/etc/localstack/init/ready.d/target/lambda.jar"
      - "./init-resources.sh:/etc/localstack/init/ready.d/init-resources.sh"

networks:
  ls_network:
    name: ls_network
```
