### ISSUE TITLE
How do you define named volumes when using GenericContainers

### ISSUE THREAD

**Issue by aruizca** [testcontainers/testcontainers-java#675]
I have an image and I can set named volumes wither using docker run:
```
docker run -it \
-p 1990:1990 \
-v docker-maven-repo:/root/.m2 \
--name my-container \
my-local-image"
```
or inside a docker-compose.yml file:
```
version: "3"
services:
  my-service:
    image: my-local-image
    volumes:
      - "docker-maven-repo:/root/.m2"
    ...
volumes:
  docker-maven-repo:
```
I don't seem to find a way to declare a named volume using GenericContainer.

Thanks for your help.
