### ISSUE TITLE
How to network a Docker-Compose Container with a BrowserWebDriverContainer?

### ISSUE THREAD

**Issue by lbier001** [testcontainers/testcontainers-java#856]
Hey all,

i'm tyring to network a Docker Compose Container with a BrowserWebDriverContainer. What is the most idiomatic way for connecting the above mentioned containers.
This is my current configuration:
```
  @ClassRule
  public static DockerComposeContainer enviroment = new DockerComposeContainer<>(new File("docker-compose.yml"))
    .withExposedService("srv", SERVER_WEB_PORT, Wait.forHttp("/portal").forStatusCode(200).withStartupTimeout(Duration.ofSeconds(160)))
    .withExposedService("srv", SERVER_MANGEMENT_PORT)
    .withExposedService("db", DB_PORT)
    .withLocalCompose(true);

  @ClassRule
  public static BrowserWebDriverContainer chrome = new BrowserWebDriverContainer<>()
    .withDesiredCapabilities(DesiredCapabilities.chrome());
```
This is my docker-compose.yml:
```
version: '2.3'

services:
  db:
    container_name: db
    image: db:latest
    ports:
      - "3306:3306"
    privileged: true

  srv:
    image: appserv:latest
    ports:
      - "8080:8080"
      - "9990:9990"
    expose:
      - 8080
      - 9990
    links:
      - db
    privileged: true
```

Or is the only way achieving this to use 2 separate GenericContainers and link them via .withNetwork() method?
