### ISSUE TITLE
[Bug]: Unable to use testcontainers in gitlab ci with elasticsearch tag 8.13.4

### ISSUE THREAD

**Issue by developerdenesh** [testcontainers/testcontainers-java#8635]
### Module

Core

### Testcontainers version

1.19.8

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host Arch

x86

### Docker version

```shell
20.0.5
```

### What happened?

Am trying to run test containers as part of a CI build on Gitlab. The project is a springboot project in kotlin. When running with an elastic image of 7.15.0 the test works fine.

Everything passes with the above. But if the elasticsearch image version is increased to say 8.13.4, the test fails.

### Relevant log output

```shell
2024-05-15T14:02:07.236Z  INFO 174 --- [demo] [    Test worker] t.d.e.c.13.4                             : Container docker.elastic.co/elasticsearch/elasticsearch:8.13.4 started in PT35.790303347S
DemoApplicationTests > testcontainerstest() FAILED
    org.apache.http.ConnectionClosedException: Connection is closed
        at app//org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:924)
        at app//org.elasticsearch.client.RestClient.performRequest(RestClient.java:304)
        at app//org.elasticsearch.client.RestClient.performRequest(RestClient.java:292)
        at app//com.example.demo.DemoApplicationTests.testcontainerstest(DemoApplicationTests.kt:41)
        Caused by:
        org.apache.http.ConnectionClosedException: Connection is closed
            at app//org.apache.http.nio.protocol.HttpAsyncRequestExecutor.endOfInput(HttpAsyncRequestExecutor.java:356)
            at app//org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:261)
            at app//org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:87)
            at app//org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:40)
            at app//org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
            at app//org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
            at app//org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
            at app//org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
            at app//org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
            at app//org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
            at app//org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
            at java.base@17.0.11/java.lang.Thread.run(Thread.java:840)
Gradle Test Executor 1 finished executing tests.
```

### Additional Information

```
package com.example.demo

import org.junit.jupiter.api.Test
import org.springframework.boot.test.context.SpringBootTest
import org.junit.jupiter.api.Assertions.assertTrue;
import org.apache.http.impl.client.BasicCredentialsProvider;
import org.testcontainers.elasticsearch.ElasticsearchContainer;
import org.apache.http.auth.AuthScope;
import org.apache.http.auth.UsernamePasswordCredentials;
import org.elasticsearch.client.RestClient;
import org.elasticsearch.client.Request;
import org.elasticsearch.client.Response;
import org.apache.http.HttpHost;

@SpringBootTest
class DemoApplicationTests {

	@Test
	fun contextLoads() {
	}

	@Test
	fun testcontainerstest() {
		val container = ElasticsearchContainer("docker.elastic.co/elasticsearch/elasticsearch:7.15.0")

		container.start()

		val credentialsProvider = BasicCredentialsProvider().apply {
			setCredentials(
				AuthScope.ANY,
				UsernamePasswordCredentials("elastic", "changeme")
			)
		}

		val client = RestClient.builder(HttpHost.create(container.httpHostAddress))
			.setHttpClientConfigCallback { httpClientBuilder ->
				httpClientBuilder.setDefaultCredentialsProvider(credentialsProvider)
			}
			.build()

		val response = client.performRequest(Request("GET", "/_cluster/health"))

		// Use the response as needed

		container.close()
		assertTrue(true);
	}
}
```

The pipeline is run as follows: 
```
image: gradle:7-jdk17

services:
  - name: docker:20.0.5-dind
    alias: docker
    command: ["--tls=false"]

variables:
  # Instruct Testcontainers to use the daemon of DinD, use port 2375 for non-tls connections.
  DOCKER_HOST: "tcp://docker:2375"
  # Instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2

stages:
  - test

test:
  stage: test
  script:
    - ./gradlew test --info
  only:
  - main
```
