### ISSUE TITLE
Unable to run mockserver container in GitLab CI

### ISSUE THREAD

**Issue by sivaprasadreddy** [testcontainers/testcontainers-java#967]
Hi,
I am building a SpringBoot application and using Gitlab CI https://gitlab.com/sivalabs/spring-boot-2-sample. I am trying to use TestContainers for **Postgres** and **mockserver** containers during integration testing. 

I have configured `.gitlab-ci.yml` as described in https://www.testcontainers.org/ci/ci.html#gitlab. But somehow it is not working. When a call is made to mockserver endpoint it is hanging forever.

```
image: docker:latest
services:
- docker:dind

variables:
  DOCKER_DRIVER: overlay2
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
- build

maven-build:
  stage: build
  script:
  - docker run -t --rm -v /var/run/docker.sock:/var/run/docker.sock -v "$(pwd)":"$(pwd)" -w "$(pwd)" -u 0:0 maven:3-jdk-8 mvn clean verify -B
```

To reproduce the error simply change `UserControllerIT` or `UserControllerRestAssuredIT` to extend `BaseTestContainerIntegrationTest`.
