### ISSUE TITLE
Native docker-compose healthcheck support

### ISSUE THREAD

**Issue by KhlaponinIO** [testcontainers/testcontainers-java#977]
Does TC support the native healthcheck in the [docker-compose](https://docs.docker.com/compose/compose-file/#healthcheck) file?

Example:
```
  userservice:
    image: 'com.foo.userservice:0.1-SNAPSHOT'
    depends_on:
      - mongodbservice
    healthcheck:
      test: curl -f http://localhost:8080/healthcheck
      interval: 5s
      retries: 20
      timeout: 90s
```
